### ISSUE TITLE
执行戳一戳操作后报错合成消息失败

### ISSUE THREAD

**Issue by HYY1116** [MistEO/Pallas-Bot#104]
报错如下
[log.txt](https://github.com/MistEO/Pallas-Bot/files/13549505/log.txt)
相关信息：
我把gocq插件卸载了，改用直接连接shamrock的形式来运行牛牛，在执行戳一戳操作时会出现

**Comment by MxEmerson** [comment]
目前暂时未对 shamrock 进行适配

**Comment by aknyzsd** [comment]
> 报错如下
> [log.txt](https://github.com/MistEO/Pallas-Bot/files/13549505/log.txt)
> 相关信息：
> 我把gocq插件卸载了，改用直接连接shamrock的形式来运行牛牛，在执行戳一戳操作时会出现

shamrock对戳一戳的定义和gocq有些区别，可以去文档里看看照着改改
