### ISSUE TITLE
自学习功能的全新概率模型

### ISSUE THREAD

**Issue by LYZhelloworld** [MistEO/Pallas-Bot#27]
## 序言
本文着重介绍了一种全新的概率模型，可以应用于带有自学习功能的QQ机器人。

## 概率基础
众所周知，各种情况的概率之和应为1，如果不为1需要进行归一化操作。本文中的所有概率均已归一化。

正常情况下，一个人看到一句话，并非一定要答复。所以原先三次重复必回答的模型是无法很好拟合现实情况的，因此应当留出至少一点概率不为零的不说话的可能。

由于一句话后面跟的另一句话重复的次数越多，发言概率越高，因此我们需要找到一种函数模型，即$y=f(x)$其中$x \rightarrow \infty$时$y \rightarrow 1$。

这里正好有这样一个模型，即$$f(x)=-\frac{1}{x}+1$$。

## 模型
需要注意的是，该模型在$x=0$时取值为负无穷，因此需要加上$x \geqslant 1$的条件。

当前一句话触发之后，后一句话应当说出的概率为：$p(x)=-\frac{1}{n}+1$，其中$n$为以前记录的前一句话后跟这句话出现的次数。

保持沉默的概率为：$$p(x')=1-\left(-\frac{1}{n}+1\right)=\frac{1}{n}$$。

对于仅出现过一次的话语，由于$p(x)$永远为0，因此不会触发。

出现两次的话，重复的概率为0.5。

如果认为该概率过高，可以考虑加一个系数$k$，使得$p(x)=k \left( -\frac{1}{n}+1 \right), 0 < k \leqslant 1$，$p(x')=1-k \left( -\frac{1}{n}+1 \right)=(1-k)+\frac{k}{n}, 0 < k \leqslant 1$。

## 带有多种选择的模型
上述模型有个问题，现实生活中一句话通常是有多个回答的。如何拟合这种情景呢？

答案是根据权重来决定各个概率的占比，并将保持沉默的概率相加。假设我们有三个事件：回复第一句话$x_1$、回复第二句话$x_2$以及保持沉默$x'$，并且两句话之前出现的次数分别为$n_1$和$n_2$，那么它们的概率分别应当为：

$$p(x_1)=\frac{n_1}{n_1+n_2}k \left( -\frac{1}{n_1}+1 \right), 0 < k \leqslant 1$$

$$p(x_2)=\frac{n_2}{n_1+n_2}k \left( -\frac{1}{n_2}+1 \right), 0 < k \leqslant 1$$

$$p(x')=\frac{n_1}{n_1+n_2}(1-p(x_1)) + \frac{n_2}{n_1+n_2}(1-p(x_2))$$

当我们有多达$m$条消息可选择时：

$$p(x_i)=\frac{n_i}{\sum_{j=1}^{m}n_j}k \left( -\frac{1}{n_i}+1 \right), 0 < k \leqslant 1$$

$$p(x')=\sum_{i=1}^{m}\frac{n_i}{\sum_{j=1}^{m}n_j}(1-p(x_i))$$

## 结语
本文提供了一种用于带有自学习功能的QQ机器人回复消息概率模型的新的设想。本文中的所有数学公式全部使用LaTeX格式存储，可以使用 https://latexeditor.lagrida.com/ 查看。

**Comment by MistEO** [comment]
咋又关了

**Comment by LYZhelloworld** [comment]
> 咋又关了

啥，你又不准备做，开着占我首页一个地方。
