### ISSUE TITLE
能否作为插件在nb的插件仓库发布呢

### ISSUE THREAD

**Issue by rainyorange** [MistEO/Pallas-Bot#29]
rt

**Comment by rainyorange** [comment]
或者把学习功能单独拿出来也行（）
https://github.com/CMHopeSunshine/LittlePaimon/issues/87#event-6951028177

**Comment by rainyorange** [comment]
另外关于mongo的使用
其实在nonebot仓库有https://github.com/nonebot/plugin-localstore
以及https://github.com/he0119/nonebot-plugin-datastore的存在

**Comment by MistEO** [comment]
现在的耦合过于严重，不光是代码层面，而是功能层面。例如 `牛牛喝酒` 会影响到学习功能的阈值，没法单独把某一个模块抽出来
