### ISSUE TITLE
能否让牛牛不复读群友发的图片

### ISSUE THREAD

**Issue by MisakaMikoto2233** [MistEO/Pallas-Bot#33]
按教程搭了一个牛牛，放群里发现经常复读群友发的图，群管理员回复“不可以”回复得嫌烦了。。。请问能不能让牛牛直接忽略掉复读图片

**Comment by MistEO** [comment]
个性化需求你可以尝试着自己改下代码，应该比较好写（

**Comment by MisakaMikoto2233** [comment]
> 个性化需求你可以尝试着自己改下代码，应该比较好写（

好的，谢谢了，主要是没学过python，好多代码不太会改（哭）
