### ISSUE TITLE
考不考虑出个部署教程视频，文字版对新手部署不太友好

### ISSUE THREAD

**Issue by Soupcpu** [MistEO/Pallas-Bot#36]
考不考虑出个部署教程视频，文字版对新手部署不太友好

**Comment by NtskwK** [comment]
一键式部署脚本做的差不多了，但是还没写对应的手册。有兴趣可以先看看
👉https://github.com/NtskwK/Pallasbot-Helper

**Comment by NtskwK** [comment]
[Pallasbot-Helper-Installer.txt](https://github.com/MistEO/Pallas-Bot/files/9410895/Pallasbot-Helper-Installer.txt)
启动器是这个，如果你对这个脚本信任，把后缀的`txt`改成`cmd`就可以运行了

**Comment by Soupcpu** [comment]
> 

您有ubuntu的部署脚本吗，我的服务器是ubuntu的

**Comment by NtskwK** [comment]
> > 
> 
> 您有ubuntu的部署脚本吗，我的服务器是ubuntu的

Ubuntu直接看原来的部署手册就好了，全是复制粘贴的事。不像win有那么多麻烦的。
