### ISSUE TITLE
关于牛牛的两个问题

### ISSUE THREAD

**Issue by Soupcpu** [MistEO/Pallas-Bot#37]
添加的nonebot插件应该放在哪，是否需要额外配置
向牛牛发送入群申请，牛牛不会自动加群，如果想设置成自动加群应该怎么操作

**Comment by MistEO** [comment]
- 添加的nonebot插件应该放在哪： src/plugins/
- 设置成自动加群： src/common/config/insert.mongodb 改改这个脚本，跑一下，mongodb的
