### ISSUE TITLE
远程访问

### ISSUE THREAD

**Issue by linzxv** [MistEO/Pallas-Bot#38]
我在vps上部署完以后，访问 `<ip>:8080/go-cqhttp/` 
- 显示：
![图片](https://user-images.githubusercontent.com/61906890/191406796-93d6bc6a-516b-4266-823e-3a103898f5ea.png)

- 防火墙是打开的，**8080** 端口也没有其他程序占用：
![图片](https://user-images.githubusercontent.com/61906890/191406919-de18c3e7-ac73-4556-a1c8-405a4cbc5f3c.png)

**请问一下支持远程访问吗**

**Comment by MistEO** [comment]
你绑定到 0.0.0.0 了吗

**Comment by linzxv** [comment]
> 你绑定到 0.0.0.0 了吗

没有，请问如何绑定

**Comment by MistEO** [comment]
- 将 `.env` 第一行改为 `ENVIRONMENT=prod`
- 将 `.env.dev` 第一行改为 `HOST=0.0.0.0`

二选一
