### ISSUE TITLE
机器人是被禁言就自己退群？

### ISSUE THREAD

**Issue by BZBY** [MistEO/Pallas-Bot#41]
突然发现自己搭的机器人退群了、、、

) 被 最弱的深境螺旋玩家禁言了 600 秒.
11-11 00:57:46 [SUCCESS] nonebot | OneBot V11 ***********| [notice.group_ban.ban]: {'time': 1***********6, 'self_id': 12***********, 'post_type': 'notice', 'notice_type': 'group_ban', 'sub_type': 'ban', 'user_id': ***********, 'group_id': ***********, 'operator_id': ***********5, 'duration': 600}
11-11 00:57:46 [DEBUG] nonebot | Checking for matchers in priority 1...
11-11 00:57:46 [DEBUG] nonebot | Checking for matchers in priority 3...
11-11 00:57:46 [DEBUG] nonebot | Checking for matchers in priority 4...
11-11 00:57:46 [DEBUG] nonebot | Checking for matchers in priority 5...
11-11 00:57:46 [DEBUG] nonebot | Checking for matchers in priority 13...
11-11 00:57:46 [DEBUG] nonebot | Checking for matchers in priority 14...
11-11 00:57:46 [INFO] nonebot | Event will be handled by Matcher(type='notice', module=src.plugins.greeting)
11-11 00:57:46 [DEBUG] nonebot | Running Matcher(type='notice', module=src.plugins.greeting)
11-11 00:57:46 [DEBUG] nonebot | Running handler Dependent(call=handle_first_receive)
11-11 00:57:46 [DEBUG] nonebot | OneBot V11 | Calling API set_group_leave
11-11 00:57:46 [INFO] nonebot | Matcher(type='notice', module=src.plugins.greeting) running complete
11-11 00:57:46 [DEBUG] nonebot | Checking for matchers in priority 15...

**Comment by MistEO** [comment]
是的，因为被踢多了容易封号，所以不如提前退了（
