### ISSUE TITLE
牛牛部署完自己不会说话（？） 教他说话也没有反应

### ISSUE THREAD

**Issue by koonoohaa** [MistEO/Pallas-Bot#42]
![image](https://user-images.githubusercontent.com/93323318/206437086-c40a65d0-cc74-40b7-ac27-ea044f8b8824.png)
![image](https://user-images.githubusercontent.com/93323318/206437511-3f8032d1-8687-4d79-abdf-2fdb7c253a9a.png)

**Comment by MistEO** [comment]
nonebot 那边启动有报错

**Comment by koonoohaa** [comment]
已经正常运行了！一天过后就开始正常说话了，功能也正常

**Comment by tianzilei** [comment]
我也遇到了同样的问题（没有文字回复，但是拍一拍有反馈），请问只需要等一段时间就可以吗？
![nblog](https://user-images.githubusercontent.com/13942076/210700123-0800d789-e7fc-4439-a70a-73b12a5833f3.png)
![gocqhttp](https://user-images.githubusercontent.com/13942076/210700161-f4781034-65e8-4435-9e2d-cd8b0fc86c8f.png)
![mongodlog](https://user-images.githubusercontent.com/13942076/210700174-e2606307-e589-44ff-bc54-8b5f98e5b08d.png)
