### ISSUE TITLE
牛牛部署后不说话

### ISSUE THREAD

**Issue by tony31444** [MistEO/Pallas-Bot#48]
不知道牛牛开发者有没有这个问题
我问了被开发者部署牛牛的那些人
他们说是一部署就可以开始学说话了
但是我家牛牛现在只会轮盘和唱歌
部署两三天了还是不会说话，更新了几个库也没反应，账号运行正常，不知道是不是正常现象

**Comment by MistEO** [comment]
现在咋样了，还有问题的话把日志也发一下，不然没法排查
