### ISSUE TITLE
更新文心API调用方式为异步

### ISSUE THREAD

**Issue by MxEmerson** [MistEO/Pallas-Bot#52]
rt，[ERNIE 3.0 API接口调用从同步预测升级为异步预测，支持未返回结果前可同时提交多个任务请求](https://wenxin.baidu.com/wenxin/docs#2l6tgx5rc)

**Comment by MistEO** [comment]
来个 PR（

**Comment by MxEmerson** [comment]
我待会儿解决一下那个卡20秒的问题再PR，太若智了

**Comment by MxEmerson** [comment]
算了，我的建议是直接放弃，文心已经寄了
![image](https://user-images.githubusercontent.com/42691763/217028923-eb42eaa4-d3ca-43be-86a7-efeb1c18fdcf.png)
