### ISSUE TITLE
按步骤部署完牛牛后 出现无法no module name 'xxx'的错误 

### ISSUE THREAD

**Issue by koonoohaa** [MistEO/Pallas-Bot#74]
首先是缺少asyncer
![image](https://user-images.githubusercontent.com/93323318/227771428-c1ef3c72-0d06-43a6-956a-e55a07b358e7.png)
然后我用pip 安装了这个模块之后 又出现了新的 模块缺少 
![image](https://user-images.githubusercontent.com/93323318/227771482-ed6d0936-2821-49dd-8de9-d1eee206f062.png)
推测不是因为少了包的原因，但是我也不知道哪里出了问题？（）

**Comment by koonoohaa** [comment]
没事了看了半天原来是AI部分的依赖缺少了（），这些报错是正常的对吗

**Comment by MistEO** [comment]
对的，不用 ai 功能可以把那几个文件夹删了
