### ISSUE TITLE
希望更多变量在提供默认值的同时支持在 `.env` 文件中更改

### ISSUE THREAD

**Issue by MxEmerson** [MistEO/Pallas-Bot#91]
如题，例如：
- `mongodb` 的 `host` 和 `port`
- `repeater` 的各种参数
- 轮盘默认踢人/禁言参数
- `chat` 的 `INIT_PROMPT` 和 `STRATEGY`
- `TTS` 声码器的选择
尽量避免直接修改源码

**Comment by MistEO** [comment]
交给你了（拍肩

**Comment by MxEmerson** [comment]
> 交给你了（拍肩

好，只是最近有点拖延症，争取国庆写好
